title: Tides
email: case@hillworks.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Coming Soon
baseurl: ""
url: https://campaign.screamat.me
github_username:  connochio

# Build settings
# theme: minima
remote_theme: just-the-docs/just-the-docs
search_enabled: true
markdown: kramdown
plugins:
  - jekyll-remote-theme
color_scheme: dark
enable_color_scheme_toggle: true
heading_anchors: true
search_enabled: true
back_to_top: true
back_to_top_text: "↑ Teleport back up"
gh_edit_link: false
#logo: "/assets/images/logo_1.png"